### ISSUE TITLE
Question about building and a game

### ISSUE THREAD

**Issue by gero** [IndiegameGarden/IndieGameGarden#1]
Hi,

I recently remembered the game Project W and am now searching for a way to get it, since the original website (creativegamechallenge.nl) has been taken offline.
This is how I found this project and what I got from reading some of the comments etc. it sounds really useful. Also seems to contain an interesting choice of games.
But I can't get it to build (after adding TTEngine to the project directory, it tells TTAudioEngine was missing, but that one should be obsolete, shouldn't it?). **What do I need to build it? Is there any documentation on that?**

Also, where does IndieGameGarden get the games from? Does it simply download them from the Zip URLs in gamelib.json? If not, or in the case that you have a backup copy of the games somewhere, **would you mind sharing Project-W with me?**
It would be awesome, if you could!

Thanks :)

**Comment by gero** [comment]
I'm sorry, I opened the issue too early. I probably sound like an idiot now.
My question about building has now shrunk to "Which version of Visual Studio do I need to get it compiling? 2015 says the project is incompatible."
I never used Visual Studio before.

I am also sorry, I got the name of TTMusicEngine wrong.

**Comment by IndiegameGarden** [comment]
It should be available here: http://indie.indiegamegarden.com/zips/project-w.zip !  It was probably built with VS 2012. But this project was never intended to be built by others - so likely some files are missing. The built version is available at http://indiegamegarden.com/ , purple icon.

**Comment by gero** [comment]
Thanks! My bad, should have thought something like this. Downloading the binary version now.
